language: php
php:
  - 7.2
  - 7.3
  - hhvm
env:
  - APP_ENV=development
  - >-
    APP_ENV=development
    CC_TEST_REPORTER_ID=f6373808e60e75764bbc04ecbaf68ea5d6fb53138d72628d582b297c43dadf5f
matrix:
  allow_failures:
    - php: hhvm
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - touch .env
  - >-
    if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo 'date.timezone =
    Europe/Berlin' >> /etc/hhvm/php.ini; fi;
  - >-
    if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'date.timezone =
    Europe/Berlin' >> ~/.phpenv/versions/$(phpenv
    version-name)/etc/conf.d/travis.ini; fi;
script:
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit;
    fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit
    --coverage-clover build/logs/clover.xml; fi;'
after_script:
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then
    vendor/bin/test-reporter; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget
    https://scrutinizer-ci.com/ocular.phar; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar
    code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php
    vendor/bin/coveralls -v; fi;'
